---
deployment:
  tasks:
    # 1. Definir la ruta y empezar
    - export DEPLOYPATH=/home/gyqjom32/public_html
    - echo "--- INICIANDO DEPLOY ---"

    # 2. Copiar archivos raíz (TODO EN UNA LÍNEA PARA EVITAR ERRORES)
    - echo "Paso 2: Copiando archivos raíz..."
    - /bin/cp -R index.html styles.css script.js terminos.html privacidad.html favicon.png .htaccess 404.html sitemap.xml assets landing-meta.html gracias.html enviar-formulario.php landing-styles.css "${DEPLOYPATH}/"
    - echo "Paso 2: ¡Archivos raíz copiados!"

    # 3. Eliminar recursos
    - echo "Paso 3: Eliminando /recursos/ anteriores..."
    - /bin/rm -rf "${DEPLOYPATH}/recursos/"
    - echo "Paso 3: ¡Directorio /recursos/ eliminado!"

    # 4. Crear recursos
    - echo "Paso 4: Creando /recursos/ nuevo..."
    - /bin/mkdir "${DEPLOYPATH}/recursos"
    - echo "Paso 4: ¡Directorio /recursos/ creado!"

    # 5. Copiar build
    - echo "Paso 5: Copiando 'build' a /recursos/..."
    - /bin/cp -R docs_irma/build/. "${DEPLOYPATH}/recursos/"
    - echo "Paso 5: ¡'build' copiado!"
    - echo "--- DEPLOY FINALIZADO CON ÉXITO ---"