---
deployment:
  tasks:
    # 1. Definir la ruta de destino final en el servidor
    - export DEPLOYPATH=/home/gyqjom32/public_html

    # 2. Sincronizar la carpeta raíz (¡usando rsync!)
    - echo "Sincronizando archivos del sitio principal..."
    - rsync -avz --delete \
        --exclude='.git' \
        --exclude='.github' \
        --exclude='.cpanel.yml' \
        --exclude='README.md' \
        --exclude='docs_irma/' \
        ./ "${DEPLOYPATH}/"

    # --- INICIO: TAREAS PARA LA DOCUMENTACIÓN (RECURSOS) ---
    # (El resto de tus tareas sigue exactamente igual)

    # 3. Eliminar la carpeta de recursos anterior para asegurar un despliegue limpio
    - echo "Eliminando el directorio de recursos anterior..."
    - /bin/rm -rf "${DEPLOYPATH}/recursos/"

    # 4. Crear la carpeta de recursos vacía nuevamente
    - echo "Creando un nuevo directorio de recursos..."
    - /bin/mkdir "${DEPLOYPATH}/recursos"

    # 5. Copiar el contenido de la carpeta 'build' a la nueva carpeta de recursos
    - echo "Copiando el sitio de documentación a la carpeta de recursos..."
    - /bin/cp -R docs_irma/build/. "${DEPLOYPATH}/recursos/"