---
deployment:
  tasks:
    # 1. Definir la ruta de destino final
    - export DEPLOYPATH=/home/gyqjom32/public_html

    # 2. Copiar los archivos de la web principal al destino
    - /bin/cp -R index.html styles.css script.js terminos.html privacidad.html favicon.png assets FAQ "${DEPLOYPATH}/"